### ISSUE TITLE
java.lang.NoClassDefFoundError when compiling using Ant 1.9.2

### ISSUE THREAD

**Issue by RichardWarburton** [real-logic/simple-binary-encoding#96]
When compiling the Java code using `ant` it compiles fine with 1.8.2, but not with 1.9.2, producing a:

```
java.lang.NoClassDefFoundError: junit/framework/JUnit4TestAdapterCache
```

This can be fixed by setting `fork="true"` on the `junit` task at line 122 of the build.xml file.  I suspect that ant 1.9.2 is trying to load its own version of junit and putting it on the classpath before the version in test/lib/.
