### ISSUE TITLE
cpp stuff fails

### ISSUE THREAD

**Issue by ivanfig** [real-logic/simple-binary-encoding#134]
Under CentOS 6.4 gcc 4.7.2 I get these errors. Any help would be appreciated.

cpp:compile:
       [cc] Starting dependency analysis for 1 files.
       [cc] 1 files are up to date.
       [cc] 0 files to be recompiled from dependency analysis.
       [cc] 1 total files to be compiled.
       [cc] /home/idf/Downloads/simple-binary-encoding/main/cpp/otf_api/Listener.cpp: In member function ‘virtual int sbe::on_the_fly::Listener::process()’:
       [cc] /home/idf/Downloads/simple-binary-encoding/main/cpp/otf_api/Listener.cpp:242:70: error: ‘__builtin_bswap16’ was not declared in this scope
       [cc] /home/idf/Downloads/simple-binary-encoding/main/cpp/otf_api/Listener.cpp:317:85: error: ‘__builtin_bswap16’ was not declared in this scope

BUILD FAILED
/home/idf/Downloads/simple-binary-encoding/build.xml:460: gcc failed with return code 1

**Comment by structurechart** [comment]
Hi, the build certainly works on 4.8 (as I tried on my box).

However, with gcc 4.6.2, I could build the release 1.1.7 which also uses __builtin_bswap16:
$ grep -r __builtin_bswap16 .
./main/cpp/otf_api/Listener.cpp:// Some GCC versions do not include __builtin_bswap16
./main/cpp/sbe/sbe.hpp:    #define SBE_BIG_ENDIAN_ENCODE_16(v) __builtin_bswap16(v)
./main/cpp/sbe/sbe.hpp:    #define SBE_LITTLE_ENDIAN_ENCODE_16(v) __builtin_bswap16(v)

It would be great if there is a solution so that more users can use this library.

Thanks!

**Comment by ivanfig** [comment]
I tried building with 4.9. I can't it to work

[idf@node1 simple-binary-encoding]$ ./gradlew 
Download https://repo1.maven.org/maven2/org/agrona/Agrona/0.5.2/Agrona-0.5.2.pom
Download https://repo1.maven.org/maven2/org/agrona/Agrona/0.5.2/Agrona-0.5.2.jar
Download https://repo1.maven.org/maven2/org/openjdk/jmh/jmh-core/1.12/jmh-core-1.12.pom
Download https://repo1.maven.org/maven2/org/openjdk/jmh/jmh-parent/1.12/jmh-parent-1.12.pom
Download https://repo1.maven.org/maven2/org/openjdk/jmh/jmh-generator-annprocess/1.12/jmh-generator-annprocess-1.12.pom
Download https://repo1.maven.org/maven2/net/sf/jopt-simple/jopt-simple/4.6/jopt-simple-4.6.pom
Download https://repo1.maven.org/maven2/org/apache/commons/commons-math3/3.2/commons-math3-3.2.pom
Download https://repo1.maven.org/maven2/org/apache/commons/commons-parent/28/commons-parent-28.pom
Download https://repo1.maven.org/maven2/org/apache/apache/13/apache-13.pom
Download https://repo1.maven.org/maven2/org/openjdk/jmh/jmh-core/1.12/jmh-core-1.12.jar
Download https://repo1.maven.org/maven2/org/openjdk/jmh/jmh-generator-annprocess/1.12/jmh-generator-annprocess-1.12.jar
Download https://repo1.maven.org/maven2/net/sf/jopt-simple/jopt-simple/4.6/jopt-simple-4.6.jar
Download https://repo1.maven.org/maven2/org/apache/commons/commons-math3/3.2/commons-math3-3.2.jar
:clean UP-TO-DATE
:sbe-all:clean UP-TO-DATE
:sbe-benchmarks:clean UP-TO-DATE
:sbe-samples:clean UP-TO-DATE
:sbe-tool:clean UP-TO-DATE
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:jar
:assemble
:compileTestJava UP-TO-DATE
:processTestResources UP-TO-DATE
:testClasses UP-TO-DATE
:test UP-TO-DATE
:check UP-TO-DATE
:build
:sbe-tool:compileJava
javac: invalid source release: 1.8
Usage: javac <options> <source files>
use -help for a list of possible options
:sbe-tool:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sbe-tool:compileJava'.
> Compilation failed with exit code 2; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 26.769 secs
[idf@node1 simple-binary-encoding]$  mkdir -p cppbuild/Debug
[idf@node1 simple-binary-encoding]$ 
[idf@node1 simple-binary-encoding]$ cd cppbuild/Debug
[idf@node1 Debug]$ cmake ../..
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /opt/rh/devtoolset-3/root/bin/cc
-- Check for working C compiler: /opt/rh/devtoolset-3/root/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /opt/rh/devtoolset-3/root/bin/c++
-- Check for working CXX compiler: /opt/rh/devtoolset-3/root/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
CMake Error at CMakeLists.txt:73 (message):
  could not find latest SBE jar in
  /home/idf/Documents/simple-binary-encoding/sbe-all/build/libs


-- Configuring incomplete, errors occurred!
See also "/home/idf/Documents/simple-binary-encoding/cppbuild/Debug/CMakeFiles/CMakeOutput.log".
See also "/home/idf/Documents/simple-binary-encoding/cppbuild/Debug/CMakeFiles/CMakeError.log".
[idf@node1 Debug]$

**Comment by structurechart** [comment]
@ivanfig seems like something wrong with your Java's setup/installation.  I installed Java 8 from Oracle instead of the stock one in CentOS 7.

@tmontgomery after quickly skimming through the code, it seems like 1.1.7 could be built because at the end the macros involving the "problematic" builtins were not interpreted?  But the latest build involves the builtins regardless of the endian-ness?

**Comment by ivanfig** [comment]
Hmmm, yeah it looks like I have OpenJDK installed:

There are 3 programs which provide 'java'.

  Selection    Command
-----------------------------------------------
   1           /usr/lib/jvm/java-1.7.0-openjdk-1.7.0.101-2.6.6.1.el7_2.x86_64/jre/bin/java
 + 2           /opt/jdk1.8.0_45/bin/java
*  3           /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.91-1.b14.el7_2.x86_64/jre/bin/java

Enter to keep the current selection[+], or type selection number:

**Comment by ivanfig** [comment]
I just changed to the Oracle java8 and I still have problems. There is a + before the 2 and an asterisk before the 3. Unfortunately it doesn't show up here.


[idf@node1 jdk1.8.0_45]$ java -version
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)
[idf@node1 jdk1.8.0_45]$ echo $JAVA_HOME
/opt/jdk1.8.0_45/jre
[idf@node1 jdk1.8.0_45]$ 

[idf@node1 jdk1.8.0_45]$ alternatives --config java

There are 3 programs which provide 'java'.

   1           /usr/lib/jvm/java-1.7.0-openjdk-1.7.0.101-2.6.6.1.el7_2.x86_64/jre/bin/java
 + 2           /opt/jdk1.8.0_45/bin/java
*  3           /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.91-1.b14.el7_2.x86_64/jre/bin/java

Enter to keep the current selection[+], or type selection number:

**Comment by tmontgomery** [comment]
All of the codecs have moved up to use C++11. This and the bswap builtins require gcc 4.8 or similar. There are no plans to make it support older compilers at this time.

**Comment by tmontgomery** [comment]
For the gradle build, you will need to setup your java environment properly to build. According to the error you see, you don't have `javac` in your path.

**Comment by ivanfig** [comment]
[idf@node1 jdk1.8.0_45]$ javac 
Usage: javac <options> <source files>
where possible options include:
  -g                         Generate all debugging info
  -g:none                    Generate no debugging info
  -g:{lines,vars,source}     Generate only some debugging info
  -nowarn                    Generate no warnings
  -verbose                   Output messages about what the compiler is doing
  -deprecation               Output source locations where deprecated APIs are used
  -classpath <path>          Specify where to find user class files and annotation processors
  -cp <path>                 Specify where to find user class files and annotation processors
  -sourcepath <path>         Specify where to find input source files
  -bootclasspath <path>      Override location of bootstrap class files
  -extdirs <dirs>            Override location of installed extensions
  -endorseddirs <dirs>       Override location of endorsed standards path
  -proc:{none,only}          Control whether annotation processing and/or compilation is done.
  -processor <class1>[,<class2>,<class3>...] Names of the annotation processors to run; bypasses default discovery process
  -processorpath <path>      Specify where to find annotation processors
  -d <directory>             Specify where to place generated class files
  -s <directory>             Specify where to place generated source files
  -implicit:{none,class}     Specify whether or not to generate class files for implicitly referenced files
  -encoding <encoding>       Specify character encoding used by source files
  -source <release>          Provide source compatibility with specified release
  -target <release>          Generate class files for specific VM version
  -version                   Version information
  -help                      Print a synopsis of standard options
  -Akey[=value]              Options to pass to annotation processors
  -X                         Print a synopsis of nonstandard options
  -J<flag>                   Pass <flag> directly to the runtime system
  -Werror                    Terminate compilation if warnings occur
  @<filename>                Read options and filenames from file

[idf@node1 jdk1.8.0_45]$

**Comment by ivanfig** [comment]
[idf@node1 jdk1.8.0_45]$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/opt/rh/devtoolset-3/root/usr/libexec/gcc/x86_64-redhat-linux/4.9.2/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/opt/rh/devtoolset-3/root/usr --mandir=/opt/rh/devtoolset-3/root/usr/share/man --infodir=/opt/rh/devtoolset-3/root/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --enable-languages=c,c++,fortran,lto --enable-plugin --with-linker-hash-style=gnu --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.9.2-20150212/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.9.2-20150212/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.9.2 20150212 (Red Hat 4.9.2-6) (GCC) 
[idf@node1 jdk1.8.0_45]$

**Comment by ivanfig** [comment]
I just installed a fresh oracle 8 JDK and I got everything to build.

Sorry, not sure what I was doing wrong before.
